
package proyectofinal;

import clases.BD;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Image;
import java.util.List;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;


public class DistribucionHabitaciones extends javax.swing.JFrame{
   private  List<JButton> botones;
    BD conn;   
  
    
   
    public DistribucionHabitaciones() throws SQLException {
        conn = new BD();       
         this.setUndecorated(true);
        initComponents();        
        this.setLocationRelativeTo(this);    
        this.btnSalir.setCursor(new Cursor(HAND_CURSOR));
        botones = new ArrayList<>();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbPisos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        cbPisos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cbPisos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Piso 1", "Piso 2" }));
        cbPisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPisosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel1.setText("Distribución de habitaciones");

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setText("X");
        btnSalir.setAlignmentX(10.0F);
        btnSalir.setAlignmentY(10.0F);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(cbPisos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 276, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnSalir))
                .addGap(18, 18, 18)
                .addComponent(cbPisos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        btnSalir.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbPisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPisosActionPerformed
        repaint();  
    }//GEN-LAST:event_cbPisosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DistribucionHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DistribucionHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DistribucionHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DistribucionHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DistribucionHabitaciones().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(DistribucionHabitaciones.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbPisos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

  public ResultSet obtenerHabitaciones(int piso) throws SQLException{
        String query = "SELECT num,tipo,estatus FROM habitacion WHERE piso="+Integer.toString(piso);
        conn.Consult(query);   
       return conn.rs;
  }
  
  public void limpiarBotones(){
       for (int i = 0; i < botones.size(); i++) 
               jPanel1.remove(botones.get(i));
  }
  
   public void paint(Graphics g){        
        super.paint(g);
           Toolkit t = Toolkit.getDefaultToolkit ();
           Image imagen[] = {t.getImage ("src/sencillaLibre.png"),t.getImage ("src/dobleLibre.png"),t.getImage ("src/tripleLibre.png"),
                                            t.getImage ("src/sencillaOcupada.png"),t.getImage ("src/dobleOcupada.png"),t.getImage ("src/tripleOcupada.png")};
           int x=0,y=1,cont=0;
            try {
                   limpiarBotones();
                ResultSet res = obtenerHabitaciones(this.cbPisos.getSelectedIndex()+1);            
                do{                    
                        int pos =  (res.getInt(3)==0) ? res.getInt(2)-1:res.getInt(2)+2;
                        g.drawImage (imagen[pos], 30+x,120*y, this);            
                        crearBoton(Integer.toString(res.getInt(1)),30+x,120*y,!res.getBoolean(3));
                        cont++;
                        x+=65;                        
                   if(x==65*7){
                       res.next();
                       pos =  (res.getInt(3)==0) ? res.getInt(2)-1:res.getInt(2)+2;
                       g.drawImage (imagen[pos], 30+x,180, this);     
                      crearBoton(Integer.toString(res.getInt(1)),30+x,180*y,!res.getBoolean(3));
                       y=2;
                       x=0;
                   }                  
                }while(res.next());
            } catch (SQLException ex) {}
         
   }

   public void crearBoton(String numH,int x,int y,boolean activar){      
         JButton boton = new JButton(numH);                
                        this.jPanel1.add(boton); 
                        boton.setLocation(x+17, y+17);
                        boton.setForeground(Color.black);
                        boton.setSize(30, 30);    
                        boton.setBackground(null);                       
                        boton.setBorder(null);                                     
                        boton.addActionListener(new ActionListener(){
                            public void actionPerformed(ActionEvent e){
                                    String num = e.getActionCommand();
                                    proyectofinal.Registro_Prueba.ventana.txtNum.setText(num);
                                   dispose();
                            }
                        });
                        boton.setEnabled(activar);
                        botones.add(boton);
   }
   
}
