/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PantallasIniciales2;

import clases.BD;
import clases.usuario;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import proyectofinal.BuscarHuesped;
import proyectofinal.ImporteActual;

/**
 *
 * @author eidan
 */
public class Principal extends javax.swing.JFrame {
 BD conn;
   
    
     public Principal(BD conexion,usuario usu) {
         this.conn = conexion;
        initComponents();
        this.setTitle("Hotel Buenavista - principal");
        this.nombreUsuario.setText(usu.getNomUsuario());     
        
    }
    public Principal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagenes/Recepcion.jpg"));
        final Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        nombreUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemGaleria = new javax.swing.JMenuItem();
        jMenuItemIngresosActuales = new javax.swing.JMenuItem();
        jMenuItemOcupHabitaciones = new javax.swing.JMenuItem();
        jMenuItemNumHabitaciones = new javax.swing.JMenuItem();
        jMenuItemOcupHotel = new javax.swing.JMenuItem();
        jMenuItemCostosHabitaciones = new javax.swing.JMenuItem();
        jMenuItemBuscarHuesped = new javax.swing.JMenuItem();
        jMenuItemRevisarHabitacion = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombreUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        nombreUsuario.setText("jLabel1");

        jDesktopPane1.setLayer(nombreUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(1265, Short.MAX_VALUE)
                .addComponent(nombreUsuario)
                .addGap(279, 279, 279))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreUsuario)
                .addContainerGap(932, Short.MAX_VALUE))
        );

        jMenuBar1.setAlignmentX(1.0F);
        jMenuBar1.setAlignmentY(1.0F);
        jMenuBar1.setAutoscrolls(true);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(260, 80));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registro.png"))); // NOI18N
        jMenu1.setText("Registro");
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salida2.png"))); // NOI18N
        jMenu2.setText("Salida");
        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Consulta.png"))); // NOI18N
        jMenu3.setText("Consulta");

        jMenuItemGaleria.setText("Galeria");
        jMenuItemGaleria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMenuItemGaleriaMouseReleased(evt);
            }
        });
        jMenu3.add(jMenuItemGaleria);

        jMenuItemIngresosActuales.setText("Ingresos Actuales");
        jMenuItemIngresosActuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIngresosActualesActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemIngresosActuales);

        jMenuItemOcupHabitaciones.setText("Ocupacion hab %");
        jMenuItemOcupHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOcupHabitacionesActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemOcupHabitaciones);

        jMenuItemNumHabitaciones.setText("Num Habitaciones");
        jMenu3.add(jMenuItemNumHabitaciones);

        jMenuItemOcupHotel.setText("Ocupacion hotel %");
        jMenuItemOcupHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOcupHotelActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemOcupHotel);

        jMenuItemCostosHabitaciones.setText("Costos habitacion");
        jMenu3.add(jMenuItemCostosHabitaciones);

        jMenuItemBuscarHuesped.setText("Buscar Huesped");
        jMenuItemBuscarHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBuscarHuespedActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemBuscarHuesped);

        jMenuItemRevisarHabitacion.setText("Revisas Habitacion");
        jMenu3.add(jMenuItemRevisarHabitacion);

        jMenuItem9.setText("Habitaciones x piso");
        jMenu3.add(jMenuItem9);

        jMenuItem1.setText("Lista Huespedes");
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.png"))); // NOI18N
        jMenu4.setText("Salir");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemIngresosActualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIngresosActualesActionPerformed
            
     try {
         new ImporteActual(this.conn).setVisible(true);
     } catch (SQLException ex) {
       
     }
        
        
        
    }//GEN-LAST:event_jMenuItemIngresosActualesActionPerformed

    private void jMenuItemOcupHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOcupHabitacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemOcupHabitacionesActionPerformed

    private void jMenuItemOcupHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOcupHotelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemOcupHotelActionPerformed

    private void jMenuItemGaleriaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemGaleriaMouseReleased
        // TODO add your handling code here:
         Galeria g = new Galeria();
         g.setSize(730,600);
         g.setResizable(false);
         g.setLocationRelativeTo(null);
         g.getContentPane().setBackground(Color.white);
         g.setVisible(true);
    }//GEN-LAST:event_jMenuItemGaleriaMouseReleased

    private void jMenuItemBuscarHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBuscarHuespedActionPerformed
        try {
         new BuscarHuesped(this.conn).setVisible(true);
     } catch (SQLException ex) {
       
     }
    }//GEN-LAST:event_jMenuItemBuscarHuespedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemBuscarHuesped;
    private javax.swing.JMenuItem jMenuItemCostosHabitaciones;
    private javax.swing.JMenuItem jMenuItemGaleria;
    private javax.swing.JMenuItem jMenuItemIngresosActuales;
    private javax.swing.JMenuItem jMenuItemNumHabitaciones;
    private javax.swing.JMenuItem jMenuItemOcupHabitaciones;
    private javax.swing.JMenuItem jMenuItemOcupHotel;
    private javax.swing.JMenuItem jMenuItemRevisarHabitacion;
    private javax.swing.JLabel nombreUsuario;
    // End of variables declaration//GEN-END:variables
}
